### ISSUE TITLE
shouldn't there be an auto_increment for primary key?

### ISSUE THREAD

**Issue by chasethenag420** [chasethenag420/sbs#10]
https://github.com/chasethenag420/sbs/blob/master/test_account.sql#L27

Looks like every table we need add auto_intcrement for primary key. check once

**Comment by chasethenag420** [comment]
@Jaswitha  is this fixed?

**Comment by Jaswitha** [comment]
Yes , Auto increment should be there for userpii table .

**Comment by Jaswitha** [comment]
do you want me to check for foreign key constraint?

**Comment by chasethenag420** [comment]
I have closed the issue I created 6 days back ;-)..that's why you got mail alert now I guess. Forget about this issue.. and yes if possible lets make foreign key constraint

**Comment by Jaswitha** [comment]
ok ill look into it.

**Comment by Jaswitha** [comment]
i made the foreign key constraint in the userpii table . i think it should
work now .There won't be any code changes.
