### ISSUE TITLE
Implement Add account button functionality to support external user transfer between his account

### ISSUE THREAD

**Issue by chasethenag420** [chasethenag420/sbs#100]

**Comment by ganeshzilpe** [comment]
I am developing this one. What are u doing in this specifically??

**Comment by chasethenag420** [comment]
Oh did you start already .. I created issue to track so we wont forget it..

**Comment by ganeshzilpe** [comment]
okay boss. :)

On Fri, Oct 23, 2015 at 12:26 PM, Nagarjuna Myla notifications@github.com
wrote:

> Oh did you start already .. I created issue to track so we wont forget it..
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/chasethenag420/sbs/issues/100#issuecomment-150669474.

## 

Thanks and Regards,
_Ganesh R Zilpe_
_Graduate Student(Computer Science)_
_Arizona State University_
_ganesh.zilpe@asu.edu ganesh.zilpe@asu.edu  |  +1-480-289-0918_
