### ISSUE TITLE
Security 3: OTP implementation

### ISSUE THREAD

**Issue by ganeshzilpe** [chasethenag420/sbs#45]

**Comment by ganeshzilpe** [comment]
Email configuration is done.
OTP is required: for transfer, credit, debit.

**Comment by chasethenag420** [comment]
How about login and signup to get rid of DOS attack

**Comment by charan1312** [comment]
We need to implement captcha right,, y cant we use catcha as a measure to prevent DOS attack?

**Comment by chasethenag420** [comment]
Otp should be there as server side validation

**Comment by ganeshzilpe** [comment]
I have implemented it with email. Its complete now.

**Comment by chasethenag420** [comment]
Hi,

I'd like to add you to my professional network on LinkedIn.
- Nagarjuna

Confirm that you know Nagarjuna: https://www.linkedin.com/e/v2?e=0-ijdiepex-5i&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=MTBJsFpr&invitationId=6093194557988622336

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ijdiepex-5i&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQFpK1hoHXHc-QAAAVI9gN-h2662sKoQakNQ0OhNbhe-CGJ_ghJcaurHNm4mz8OtB8n2_N-hHBl8K4IbNdGp1bqLj24MWPaF5eStj-d6NsKI0B1lPNtVdnLhxlZBxGxbPAdOQOy6k0srDrTszkqE-_silwd7nBFo3xgL3wb4HboT1HS1AtZ2b6iU50x5LOrYmTCX&eid=0-ijdiepex-5i

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ijdiepex-5i&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by chasethenag420** [comment]
Nagarjuna Myla would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=z9oxc8-ijn3w9uv-jr&a=preRegInvite&ek=first_guest_reminder_01&li=14&m=hero&ts=accept_text&sharedKey=MTBJsFpr&invitationID=6093194557988622336

View Nagarjuna Myla&#39;s profile: https://www.linkedin.com/e/v2?e=z9oxc8-ijn3w9uv-jr&a=preRegInvite&ek=first_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=MTBJsFpr&invitationID=6093194557988622336

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=z9oxc8-ijn3w9uv-jr&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=z9oxc8-ijn3w9uv-jr&loid=AQHpY5wMiwDGkAAAAVJg3nupYh_wQZ2kqkT4MWho4hoX96yYC-ZiSs3FMpgq96uPpBZKgokg5bc2MmIbROyKJVDuhHn8KyaU6jnlxoE3YK1li-WiAZKOn5vVZcicUZynyNX2w0Tfc7Tzlid8JAn-AUi8QIpwkZ3h-aljoULNnTWoQlmYAQ7qFJOYGP747ksRQ4i5

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=z9oxc8-ijn3w9uv-jr&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by chasethenag420** [comment]
Nagarjuna Myla would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=z9oxc8-ijx3mpru-lt&a=preRegInvite&ek=second_guest_reminder_01&li=13&m=hero&ts=accept_text&sharedKey=MTBJsFpr&invitationID=6093194557988622336

View Nagarjuna Myla&#39;s profile: https://www.linkedin.com/e/v2?e=z9oxc8-ijx3mpru-lt&a=preRegInvite&ek=second_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=MTBJsFpr&invitationID=6093194557988622336

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=z9oxc8-ijx3mpru-lt&t=lun&midToken=AQFmrFVhGEd36Q&ek=second_guest_reminder_01&li=15&m=unsub&ts=HTML&eid=z9oxc8-ijx3mpru-lt&loid=AQHgs-WQseqn-gAAAVKE767XXZBHDAyYcmb7_Rr0fe23SyMe5ruy_L3CK7BBpwnIaRvVgQmcj08amlU913XH4apoSUghrLs3MjaqSHRYAgv7GgJJcBX5jlWef0_ayEEYYeZmn0fCGLZl4bNzYWhL4LvdB0szq2Oz5hTSNcmckAkmIVaG02VZMn3JOr2fWNuiG4-a

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=z9oxc8-ijx3mpru-lt&a=customerServiceUrl&ek=second_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.
