### ISSUE TITLE
Do software setup on VM

### ISSUE THREAD

**Issue by chasethenag420** [chasethenag420/sbs#57]

**Comment by charan1312** [comment]
I guess Nagarjuna finished it...?

**Comment by chasethenag420** [comment]
Yes but Do not close it until we test everything

**Comment by chasethenag420** [comment]
Hi,

I'd like to add you to my professional network on LinkedIn.
- Nagarjuna

Confirm that you know Nagarjuna: https://www.linkedin.com/e/v2?e=0-ijdiept0-py&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=gDIl9WFu&invitationId=6093194558143815681

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ijdiept0-py&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQGZ-dmnwQJZzQAAAVI9gOCoFP0HiRfeixjNCfJlql2xWgjW_TuUPt00H8yGUJTUrEM8V8Vx4Eky_rI0wPOE2KwLTMQlGHsQEL7WraJBiPvkEAQtmK3Z2mEyfUMSoeHt26jOYri2bczVs5TpTeazIJFbc8rvrAhc15SqM2mUtI_0Ma_XQmDfrB24plSw1gNcMm4X&eid=0-ijdiept0-py

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ijdiept0-py&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by chasethenag420** [comment]
Hi Ganesh,

The email address reply@reply.github.com was recently added to your LinkedIn account.

If you don&#39;t want that email associated with your account after all, here&#39;s how to remove it:

Type https://www.linkedin.com/e/v2?e=60db7f-ijdwy71e-k4&amp;t=nas&amp;midToken=AQHVM8ohuqEp4w&amp;ek=security_add_email_notification into your browser
Sign in with your email address and password
Find Primary email in the upper left and click Change/Add
Click Remove next to the email address you&#39;re removing.

Thanks for using LinkedIn and for helping us to keep your account secure.
The LinkedIn Team

This email was intended for Ganesh Zilpe (Software Developer Intern at Edupoint Educational Systems, LLC). 
Learn why we included this: https://www.linkedin.com/e/v2?e=60db7f-ijdwy71e-k4&a=customerServiceUrl&midToken=AQHVM8ohuqEp4w&ek=security_add_email_notification&articleId=4788

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=60db7f-ijdwy71e-k4&a=customerServiceUrl&midToken=AQHVM8ohuqEp4w&ek=security_add_email_notification

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.
