### ISSUE TITLE
Do SSL setup on tomcat and enable application only on 443 port

### ISSUE THREAD

**Issue by chasethenag420** [chasethenag420/sbs#58]

**Comment by charan1312** [comment]
Currently it is enabled on the 8443 port,, also 8080 is enabled as of now... we can change it to 443 and disable 8080.... key and crt file are in /home/ubuntu/sbskeys1/

**Comment by chasethenag420** [comment]
We have apache server as well to work with mysql on ubunutu we will should
stop that service when we are deploying on finally

**Comment by chasethenag420** [comment]
Hi,

I'd like to add you to my professional network on LinkedIn.
- Nagarjuna

Confirm that you know Nagarjuna: https://www.linkedin.com/e/v2?e=0-ijdiepuv-bt&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=fLV_vC5x&invitationId=6093194557661470720

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ijdiepuv-bt&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQHEjGZIf9ga1QAAAVI9gN76xWg0kczurc4jluaRAxp1lHKqh2g2-fztZDxfrGiKPgRDKwBG88HivnwUVkrBadVUrLm_JaVjPrtYDFd74jqy3apFMs5S7J4xeQPC0WDEZ6I2ntc1jLg2b7OxEEBrE6ZLtHudjyK7ZDr0K2xaSMQ0I3RGXr0LIbtqsK6tHZROhg_g&eid=0-ijdiepuv-bt

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ijdiepuv-bt&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by chasethenag420** [comment]
Nagarjuna Myla would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=-gavkdt-ijn3w6y6-b1&a=preRegInvite&ek=first_guest_reminder_01&li=14&m=hero&ts=accept_text&sharedKey=fLV_vC5x&invitationID=6093194557661470720

View Nagarjuna Myla&#39;s profile: https://www.linkedin.com/e/v2?e=-gavkdt-ijn3w6y6-b1&a=preRegInvite&ek=first_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=fLV_vC5x&invitationID=6093194557661470720

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-gavkdt-ijn3w6y6-b1&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=-gavkdt-ijn3w6y6-b1&loid=AQGFo8WykG9V_AAAAVJg3zhSWR85N7-G2cHGwvcc3YMFYn2v99VtR0EfYJiK2kb488x0c5NhleqrOVO8HGLSBLiQWlDRCvGwXd4gWeIJNocIuP3CjJuC87Pxv3Vd1VkdszXTIipWGjFobVS7A7YtmDHs0lIRYiD0GzIN_H0aJ5NohAYYqz_OrTKOkuBLHs8nKB_D

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-gavkdt-ijn3w6y6-b1&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.
